apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  config.yaml: |
    mongodb:
      connectionString: "mongodb://<username>:<password>@<mongodb-host>:<port>/<database-name>"
